version: "3.9"

services:
  user-profile-api:
    build: .
    container_name: user-profile-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000
